
import React from 'react';
import { createRoot } from 'react-dom/client';
import { Droplets, ShieldCheck, Wrench, Home, Star, CheckCircle2, Phone } from 'lucide-react';
import './style.css';
const img='/images/';
function App(){
const services=[
 {title:'Whole-Home Filtration',image:'whole-home-system.png',items:['Filters water before it reaches every faucet','Targets chlorine taste, odor and sediment','Built for Bay Area homes and families']},
 {title:'Water Softener Systems',image:'softener-system.png',items:['Helps reduce scale buildup on fixtures','Better shower feel for hair and skin','Protects appliances and plumbing over time']},
 {title:'Reverse Osmosis Drinking Water',image:'reverse-osmosis-system.png',items:['Clean, crisp water at the kitchen sink','Helps reduce bottled water dependence','Compact under-sink design with modern faucet']}
];
const areas=['San Francisco','Daly City','San Mateo','Burlingame','Redwood City','Palo Alto','San Jose','Marin','East Bay'];
return <>
 <div className="topbar">Bay Area whole-home water filtration consultations • Financing options available</div>
 <nav className="nav"><div className="nav-inner"><a className="brand" href="#home"><img src={img+'logo-golden-crest.png'}/><div><div className="brand-title">Golden Crest Water</div><div className="brand-sub">BAY AREA WATER SYSTEMS</div></div></a><div className="links"><a href="#systems">Systems</a><a href="#process">How It Works</a><a href="#areas">Service Areas</a><a href="#gallery">Gallery</a><a href="#quote">Get Quote</a></div><a className="btn" href="#quote">Free Water Check</a></div></nav>
 <main id="home" className="hero"><div className="hero-grid"><div><span className="eyebrow">Bay Area Whole-Home Water Treatment</span><h1>Cleaner, softer water for your entire home.</h1><p>Golden Crest Water helps homeowners upgrade from hard, chlorine-heavy tap water to professionally installed filtration, softener and reverse osmosis systems.</p><div className="actions"><a className="btn" href="#quote">Book Free Consultation</a><a className="btn secondary" href="#systems">View Systems</a></div></div><div className="hero-card"><img src={img+'golden-install-double-system.jpg'} alt="Installed whole-home water treatment system"/></div></div></main>
 <section className="trust"><div className="trust-card"><ShieldCheck/><b>Quality Equipment</b><span>Dealer-backed water systems.</span></div><div className="trust-card"><Wrench/><b>Professional Installation</b><span>Installed by local licensed pros.</span></div><div className="trust-card"><Star/><b>Local Service</b><span>Bay Area support from start to finish.</span></div><div className="trust-card"><Home/><b>Family-Owned Feel</b><span>No corporate pressure tactics.</span></div></section>
 <section className="section blue-section"><div className="wrap split"><div><span className="eyebrow">The Problem</span><h2>Most Bay Area homes still rely on untreated tap water.</h2><p>Even when water is considered safe, many homeowners still deal with chlorine smell, scale buildup, dry skin, rough laundry, appliance wear and bad-tasting drinking water.</p></div><div className="problem-list">{['White scale on faucets and shower glass','Chlorine taste or smell','Dry skin and hair after showering','Buying cases of bottled water','Concern about old plumbing and sediments'].map(x=><div className="problem" key={x}><CheckCircle2 size={18}/> {x}</div>)}</div></div></section>
 <section id="systems" className="section"><div className="wrap"><div className="section-head"><span className="eyebrow">Systems</span><h2>Built around what your home actually needs.</h2><p>Start with a simple consultation and match the system to your water, household size and goals.</p></div><div className="grid3">{services.map(s=><div className="service" key={s.title}><img src={img+s.image}/><h3>{s.title}</h3><ul>{s.items.map(i=><li key={i}>{i}</li>)}</ul></div>)}</div></div></section>
 <section id="process" className="section blue-section"><div className="wrap"><div className="section-head"><span className="eyebrow">How It Works</span><h2>A simple process from quote to clean water.</h2></div><div className="steps">{['Free water consultation','System recommendation','Professional installation','Enjoy better water'].map((s,i)=><div className="step" key={s}><div className="num">{i+1}</div><h3>{s}</h3><p>{['We learn your water goals, home setup and service area.','We recommend filtration, softening, RO or a full-home package.','A local licensed pro handles the install cleanly and professionally.','Enjoy better showers, drinking water and appliance protection.'][i]}</p></div>)}</div></div></section>
 <section id="gallery" className="section"><div className="wrap"><div className="section-head"><span className="eyebrow">Install Gallery</span><h2>Clean installs designed to fit real homes.</h2><p>Garage, side-yard and utility-area installs for homeowners across the Bay Area.</p></div><div className="gallery">{['golden-install-clean-wall.jpg','golden-install-corner-system.jpg','golden-install-double-system.jpg','golden-install-outdoor-brick.jpg','golden-install-single-garage.jpg'].map(x=><img key={x} src={img+x}/>)}</div></div></section>
 <section id="areas" className="section blue-section"><div className="wrap split"><div><span className="eyebrow">Service Areas</span><h2>Serving homeowners across the Bay Area.</h2><p>Golden Crest Water is based for Peninsula and Bay Area coverage, with consultations available across nearby cities.</p></div><div className="grid3">{areas.map(a=><div className="problem" key={a}>{a}</div>)}</div></div></section>
 <section id="quote" className="section"><div className="wrap cta"><div><h2>Ready to find out what your home needs?</h2><p>Request a free consultation and we’ll help you compare options for whole-home filtration, softening and drinking water.</p><p className="small">Replace this form with your GoHighLevel embed when ready.</p></div><form className="form"><input placeholder="Full name"/><input placeholder="Phone number"/><input placeholder="City"/><select><option>What are you interested in?</option><option>Whole-home filtration</option><option>Water softener</option><option>Reverse osmosis</option><option>Not sure yet</option></select><textarea rows="4" placeholder="Tell us what you want improved about your water"></textarea><button className="btn" type="button"><Phone size={18}/> Request Quote</button></form></div></section>
 <footer className="footer"><div className="footer-inner"><div><b>Golden Crest Water</b><div className="small">Whole-home water filtration, softeners and RO systems for Bay Area homeowners.</div></div><div className="small">Service-area business • Bay Area, CA<br/>© {new Date().getFullYear()} Golden Crest Water. All rights reserved.</div></div></footer>
 </>}
createRoot(document.getElementById('root')).render(<App/>);
