import React from 'react'
import { createRoot } from 'react-dom/client'
import { Phone, Droplets, ShieldCheck, Star, Home, Wrench, MapPin, CheckCircle, Menu, ArrowRight, Sparkles } from 'lucide-react'
import './index.css'

const phone = '415-378-0179'
const cleanPhone = phone.replace(/-/g, '')
const img = (name) => `/images/${name}`

const serviceAreas = ['San Francisco','Daly City','San Mateo','Burlingame','Oakland','Berkeley','San Rafael','Mill Valley','San Jose','Walnut Creek','Fremont','Palo Alto']
const products = [
  {
    title:'Complete Home System Package',
    tag:'Best Seller',
    image:'whole-home-system.png',
    description:'A full-home water treatment solution built to improve water quality at the main point of entry, helping your entire home enjoy cleaner, softer water.',
    bullets:['Whole-home treatment','Cleaner showers','Better taste and smell','Appliance protection']
  },
  {
    title:'Water Softener with Chlorine Filtration',
    tag:'Family Favorite',
    image:'softener-system.png',
    description:'Designed to reduce hardness and chlorine so your water feels better on skin, hair, dishes, laundry, and plumbing fixtures.',
    bullets:['Softer skin and hair','Less scale buildup','Cleaner dishes','Lower soap usage']
  },
  {
    title:'Tankless Reverse Osmosis Drinking System',
    tag:'Drinking Water Upgrade',
    image:'reverse-osmosis-system.png',
    description:'A sleek under-sink drinking water system for crisp, clean water straight from the tap.',
    bullets:['Great-tasting water','Under-sink design','Daily drinking water','Modern filtration']
  }
]
const installs = [
  ['install-single-garage.jpg'],
  ['install-double-system.jpg'],
  ['install-outdoor-brick.jpg'],
  ['install-clean-wall.jpg'],
  ['install-corner-system.jpg'],
  ['kitchen-clean-water.jpg']
]
const faqs = [
  ['Do you service all of the Bay Area?','Yes. We serve homes across San Francisco and most Bay Area cities within roughly 60 to 90 minutes of San Francisco.'],
  ['Is installation included?','Most systems can be professionally installed by a licensed local installer. Exact installation details depend on your home setup and system selection.'],
  ['Will this help with hard water?','Yes. Whole-home softening and filtration systems are designed to reduce hardness, chlorine taste and smell, sediment, and common water quality issues depending on the selected package.'],
  ['How fast can I get a quote?','Submit a quote request or call directly and we will help you figure out the right setup for your home as quickly as possible.']
]

function Button({children, variant='primary'}){
  const styles = variant === 'primary' ? 'bg-sky-600 text-white hover:bg-sky-700 shadow-lg shadow-sky-600/20' : 'bg-white text-slate-900 border border-slate-200 hover:border-sky-500 hover:text-sky-700'
  return <a href="#quote" className={`inline-flex items-center justify-center rounded-full px-6 py-3 text-sm font-semibold transition-all duration-200 ${styles}`}>{children}</a>
}
function TrustCard({icon:Icon,title,text}){return <div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-sky-50 text-sky-700"><Icon size={22}/></div><div><h3 className="text-sm font-bold text-slate-950">{title}</h3><p className="text-xs text-slate-500">{text}</p></div></div>}

function App(){return <main className="min-h-screen bg-white text-slate-950">
  <div className="bg-sky-700 px-4 py-3 text-center text-sm font-semibold text-white">Save up to 40% on complete home water systems for Bay Area homeowners</div>
  <header className="sticky top-0 z-50 border-b border-slate-200 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 lg:px-8"><a href="#" className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-sky-600 text-white"><Droplets size={24}/></div><div className="leading-tight"><div className="text-lg font-black tracking-tight">Honest Water Co</div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-sky-700">San Francisco Dealer</div></div></a><nav className="hidden items-center gap-7 text-sm font-semibold text-slate-700 lg:flex"><a href="#products" className="hover:text-sky-700">Products</a><a href="#areas" className="hover:text-sky-700">Service Areas</a><a href="#process" className="hover:text-sky-700">How It Works</a><a href="#gallery" className="hover:text-sky-700">Gallery</a><a href="#faq" className="hover:text-sky-700">FAQs</a></nav><div className="hidden items-center gap-4 lg:flex"><a href={`tel:${cleanPhone}`} className="flex items-center gap-2 text-sm font-bold text-slate-900"><Phone size={17}/> {phone}</a><Button>Quick Quote</Button></div><button className="rounded-full border border-slate-200 p-2 lg:hidden"><Menu size={22}/></button></div></header>
  <section className="bg-gradient-to-b from-sky-50 via-white to-white px-4 py-8 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-2 lg:grid-cols-4"><TrustCard icon={ShieldCheck} title="Lifetime Warranty" text="Clean water protection for life"/><TrustCard icon={Wrench} title="Professional Installation" text="Installed by local licensed pros"/><TrustCard icon={Star} title="Trusted Product Line" text="Dealer-backed systems and support"/><TrustCard icon={Home} title="Family-Owned Service" text="Local Bay Area care and follow-up"/></div></section>
  <section className="px-4 pb-20 pt-10 lg:px-8 lg:pb-28"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_0.95fr]"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-sky-200 bg-sky-50 px-4 py-2 text-sm font-bold text-sky-800"><Sparkles size={16}/> Bay Area whole-home water treatment</div><h1 className="max-w-4xl text-5xl font-black tracking-tight text-slate-950 md:text-6xl lg:text-7xl">Trusted Water Treatment & Filtration Services in San Francisco</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Get cleaner, softer, better-tasting water throughout your entire home with Honest Water Co systems — now available for San Francisco and Bay Area homeowners through your local dealer.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button>Get My Free Quote <ArrowRight className="ml-2" size={18}/></Button><a href={`tel:${cleanPhone}`} className="inline-flex items-center justify-center rounded-full border border-slate-200 bg-white px-6 py-3 text-sm font-semibold text-slate-900 hover:border-sky-500 hover:text-sky-700">Call {phone}</a></div><p className="mt-5 text-sm font-medium text-slate-500">Serving homes within roughly 60–90 minutes of San Francisco.</p></div><div className="relative"><div className="absolute -inset-4 rounded-[2rem] bg-sky-200/40 blur-3xl"/><div className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-white p-5 shadow-2xl"><div className="rounded-[1.5rem] bg-gradient-to-br from-sky-50 to-white p-8"><img src={img('honest-water-ro-system.png')} alt="Honest Water reverse osmosis system" className="hero-img mx-auto h-[520px] w-auto max-w-full object-contain"/></div></div></div></div></section>
  <section id="products" className="bg-slate-50 px-4 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-black uppercase tracking-[0.25em] text-sky-700">Our most popular systems</p><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">Whole-home water solutions built for Bay Area families.</h2><p className="mt-5 text-lg text-slate-600">From showers to drinking water, we help homeowners choose the right system for their home, budget, and water quality goals.</p></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{products.map((p)=><article key={p.title} className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="mb-5 inline-flex rounded-full bg-sky-50 px-3 py-1 text-xs font-black uppercase tracking-wider text-sky-700">{p.tag}</div><div className="mb-6 flex aspect-[4/3] items-center justify-center overflow-hidden rounded-3xl bg-gradient-to-br from-slate-50 to-white p-6"><img src={img(p.image)} alt={p.title} className="h-full w-full object-contain"/></div><h3 className="text-2xl font-black tracking-tight">{p.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{p.description}</p><ul className="mt-5 grid gap-3">{p.bullets.map(b=><li key={b} className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CheckCircle size={17} className="text-sky-600"/> {b}</li>)}</ul><div className="mt-6"><Button>Request Quote</Button></div></article>)}</div></div></section>
  <section id="process" className="px-4 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-sm font-black uppercase tracking-[0.25em] text-sky-700">Simple process</p><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">From quick quote to clean water.</h2><p className="mt-5 text-lg leading-8 text-slate-600">We keep the process simple, local, and transparent so you can make a confident decision without pressure.</p></div><div className="grid gap-5 md:grid-cols-3">{[['01','Request a Quote','Tell us about your home and what you want improved.'],['02','Match the System','We recommend the right whole-home or drinking water setup.'],['03','Install & Enjoy','A professional installer completes the setup and you enjoy better water.']].map(([n,t,tx])=><div key={t} className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="text-sm font-black text-sky-700">{n}</div><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{tx}</p></div>)}</div></div></section>
  <section id="areas" className="bg-sky-700 px-4 py-20 text-white lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><MapPin className="mb-4" size={34}/><h2 className="text-4xl font-black tracking-tight md:text-5xl">Serving San Francisco and the greater Bay Area.</h2><p className="mt-5 text-lg leading-8 text-sky-50">We help homeowners across the Bay Area within roughly an hour to an hour and a half from San Francisco.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{serviceAreas.map(a=><div key={a} className="rounded-2xl bg-white/10 px-4 py-3 text-sm font-bold backdrop-blur">{a}</div>)}</div></div></div></section>
  <section id="gallery" className="px-4 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-black uppercase tracking-[0.25em] text-sky-700">Install gallery</p><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">Real installs. Clean setups. Better water.</h2></div><a href="#quote" className="inline-flex items-center justify-center rounded-full bg-sky-600 px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-sky-600/20 transition-all duration-200 hover:bg-sky-700">Schedule My Install</a></div><div className="mt-10 grid gap-5 md:grid-cols-3">{installs.map(([src,alt],i)=><div key={src} className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><img src={img(src)} alt={alt} className={`install-img aspect-[4/3] h-full w-full object-cover transition duration-300 hover:scale-105 ${i===2?'left':''}`}/></div>)}</div></div></section>
  <section id="faq" className="bg-slate-50 px-4 py-20 lg:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-sm font-black uppercase tracking-[0.25em] text-sky-700">FAQs</p><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">Common questions answered.</h2></div><div className="mt-10 grid gap-4">{faqs.map(([q,a])=><div key={q} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-lg font-black">{q}</h3><p className="mt-3 leading-7 text-slate-600">{a}</p></div>)}</div></div></section>
  <section id="quote" className="px-4 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[2rem] bg-slate-950 shadow-2xl lg:grid-cols-2"><div className="p-8 text-white md:p-12"><p className="text-sm font-black uppercase tracking-[0.25em] text-sky-300">Quick quote</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-5xl">Ready to enjoy cleaner water?</h2><p className="mt-5 text-lg leading-8 text-slate-300">Call now or request a free quote and we’ll help you choose the right system for your home.</p><a href={`tel:${cleanPhone}`} className="mt-8 inline-flex items-center gap-3 rounded-full bg-white px-6 py-3 text-sm font-black text-slate-950"><Phone size={18}/> {phone}</a></div><form className="grid gap-4 bg-white p-8 md:p-12"><input className="rounded-2xl border border-slate-200 px-4 py-4 text-sm outline-none focus:border-sky-500" placeholder="Full name"/><input className="rounded-2xl border border-slate-200 px-4 py-4 text-sm outline-none focus:border-sky-500" placeholder="Phone number"/><input className="rounded-2xl border border-slate-200 px-4 py-4 text-sm outline-none focus:border-sky-500" placeholder="City"/><select className="rounded-2xl border border-slate-200 px-4 py-4 text-sm outline-none focus:border-sky-500"><option>What are you interested in?</option><option>Whole-home filtration</option><option>Water softener</option><option>Reverse osmosis drinking water</option><option>Not sure yet</option></select><textarea className="min-h-28 rounded-2xl border border-slate-200 px-4 py-4 text-sm outline-none focus:border-sky-500" placeholder="Tell us about your water concerns"/><button type="button" className="rounded-full bg-sky-600 px-6 py-4 text-sm font-black text-white hover:bg-sky-700">Submit Quote Request</button></form></div></section>
  <footer className="border-t border-slate-200 px-4 py-12 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-4"><div className="md:col-span-2"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-sky-600 text-white"><Droplets size={24}/></div><div><div className="font-black">Honest Water Co SF</div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-sky-700">Local Dealer</div></div></div><p className="mt-5 max-w-md leading-7 text-slate-600">Family-owned local dealer helping San Francisco and Bay Area homeowners upgrade to cleaner, softer, better-tasting water.</p></div><div><h3 className="font-black">Helpful Links</h3><div className="mt-4 grid gap-3 text-sm font-semibold text-slate-600"><a href="#products">Products</a><a href="#areas">Service Areas</a><a href="#process">How It Works</a><a href="#faq">FAQs</a></div></div><div><h3 className="font-black">Contact</h3><div className="mt-4 grid gap-3 text-sm font-semibold text-slate-600"><a href={`tel:${cleanPhone}`}>{phone}</a><span>San Francisco, CA</span><span>Bay Area Service</span></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-slate-200 pt-6 text-sm text-slate-500">© 2026 Honest Water Co SF. Local independent dealer.</div></footer>
  <div className="fixed bottom-4 left-4 right-4 z-50 rounded-full bg-sky-600 p-2 shadow-2xl lg:hidden"><a href={`tel:${cleanPhone}`} className="flex items-center justify-center gap-2 rounded-full py-3 text-sm font-black text-white"><Phone size={18}/> Call for Quick Quote</a></div>
</main>}

createRoot(document.getElementById('root')).render(<App />)
